### ISSUE TITLE
Merge sort.cpp

### ISSUE THREAD

**Issue by Aastha26-lab** [MLSA-Mehran-UET/learn2code#10]

**Comment by ayeshatahirme** [comment]
Hi! I would like to work on it.

**Comment by chetan-2002** [comment]
Hey, I am very excited to take up this issue. @mursalfk Can you please assign this issue to me?

**Comment by mursalfk** [comment]
Sure thing. Please take up the issue. @chetan-2002

**Comment by chetan-2002** [comment]
Hey @mursalfk, I just wanted to confirm that I can only contribute if an issue is assigned to me or can I create my own issues and make a worth pull request for that issue?

**Comment by mursalfk** [comment]
No. You can contribute to any issue by creating a new one, if not already available.
